package com.timepalette.daylogue.model.enums.auth;

public enum AuthAuditEvent {

    SIGNUP,
    LOGIN_SUCCESS, LOGIN_FAIL,
    LOGOUT,
    REFRESH_SUCCESS, REFRESH_FAIL,
    PW_CHANGE, PW_RESET_REQUEST, PW_RESET_CONFIRM,
    EMAIL_VERIFY_REQUEST, EMAIL_VERIFY_CONFIRM,
    SOCIAL_LINK, SOCIAL_UNLINK, SOCIAL_LOGIN_SUCCESS, SOCIAL_LOGIN_FAIL,
    PROFILE_UPDATE
}
