package com.timepalette.daylogue.model.enums.common;

public enum AuthErrorCode {

    INVALID_REQUEST,
    INVALID_EMAIL,
    INVALID_PASSWORD_POLICY,

    EMAIL_ALREADY_USED,

    LOGIN_FAILED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_DELETED,
    EMAIL_NOT_VERIFIED,

    TOO_MANY_ATTEMPTS,

    TOKEN_INVALID,
    TOKEN_EXPIRED,
    TOKEN_ALREADY_USED,

    AUTH_THROTTLED,

    REFRESH_REVOKED,
    AUTH_ACCOUNT_DISABLED, AUTH_LOGIN_FAILED, AUTH_REFRESH_INVALID, AUTH_PASSWORD_POLICY
}
